### PR TITLE
Make header and footer imports

### LINKED ISSUE #2: Footer is constant
The footer is constant on each page. This means that if the footer needs to be changed, it will have to be changed on each page. Something should be used so that there is one footer file and one change to it will affect all pages.

### PR DESCRIPTION
**Pull request by Accio1**
-Make the header and footer imports so that one change will affect all pages.
-Only the footer is imported on the main page, because the header has extra information.
-Does not apply to 404 page yet.

Resolves #2

@leahcimto

### CODE REVIEW

**Comment by leahcimto** [comment]
I'll review this tomorrow

**Review by leahcimto — COMMENTED** [review]
Everything looks awesome! One small thing though (doesn't relate to header and footer but I think it would be better if it was addressed here since it is so small), could you make css for the button cursor: pointer;?

**Comment by Accio1** [comment]
@leahcimto I just updated the CSS. The button to close the disclaimer is now cursor: pointer on hover.

**Review by leahcimto — APPROVED** [review]
Looks good!

**Pull request merged**
